version: "3.8"

services:
  llm-ninja:
    build:
      context: .. # 指向项目根目录，即 /var/app/edu_rag_ai
      dockerfile: docker/Dockerfile # Dockerfile路径，即 /var/app/edu_rag_ai/docker/Dockerfile
    ports:
      - "8010:8010"
    volumes:
      # 宿主机路径 (相对于 docker-compose.yml) : 容器内部路径
      - ../chroma_db:/app/chroma_db
      - ../data:/app/data
      - ../index_store:/app/index_store
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

# 在文件底部定义命名卷
volumes:
  chroma_db_volume:
  data_volume:
  index_store_volume:
